### ISSUE TITLE
symmetric_matrices function not creating matrices as it should

### ISSUE THREAD

**Issue by juaolobo** [data-apis/array-api-tests#105]
I was implementing the eigvalsh function in a repository following the Array API standard and had some issues when testing, because of the `symmetric_matrices` function. 

The first thing is that infinite values are being allowed on the creation of the matrices. This is really weird because the `elements` dictionary is being constructed with `allow_infinity : False` and passed as a parameter to the creation function, but the resulting matrices are getting infinite values nonetheless.

The other thing is that, now, the logic for producing a symmetric matrix is to get the triangular upper when diagonal=0 of a random matrix, get the triangular upper when diagonal=1 and add the first one and the transpose of the second one. This is creating an issue because when you have more than two dimensions, the transpose operation takes all dimensions into account, not only the last two and, at the end of the function, that leads to an attempt to create a matrix that is not of the shape (..., N, N). One example of this happening is a particular case that I came across where the first tensor's shape was (0, 2, 2) and after transposing, its shape turned to (2, 2, 0) and when we tried to return their addition, it caused a crash due to broadcasting error.

**Comment by honno** [comment]
> The first thing is that infinite values are being allowed on the creation of the matrices. This is really weird because the `elements` dictionary is being constructed with `allow_infinity : False` and passed as a parameter to the creation function, but the resulting matrices are getting infinite values nonetheless.

Hmm, I can't seem the reproduce that `test_eigvalsh` will generate arrays with non-finite values.

> This is creating an issue because when you have more than two dimensions, the transpose operation takes all dimensions into account, not only the last two and, at the end of the function, that leads to an attempt to create a matrix that is not of the shape (..., N, N).

What you say makes sense, but I couldn't reproduce this either (i.e. by running `array_api_tests/meta/test_hypothesis_helpers.py::test_symmetric_matrices --max-examples 10000`). Linalg is more @asmeurer's wheelhouse—any thoughts?

Also maybe worth noting that the test suite gets updated frequently—maybe something Aaron pushed recently fixed these issues?

**Comment by juaolobo** [comment]
Ive been doing some testing and research and it was indeed my mistake, I will be closing the issue. Thanks for the response!
