### ISSUE TITLE
test_prod failing for PyTorch due to unsupported dtypes

### ISSUE THREAD

**Issue by djl11** [data-apis/array-api-tests#106]
Despite the useful updates referenced in this [issue](https://github.com/data-apis/array-api-tests/issues/10), the prod test is still failing [on this line](https://github.com/data-apis/array-api-tests/blob/605621381a48d0373ef40f3f88b217cb817e0404/array_api_tests/test_statistical_functions.py#L147) with a PyTorch backend, even with `FILTER_UNDEFINED_DTYPES = True` and flag `-k "not (uint16 or uint32 or uint64)"`

The error is: `AssertionError: out.dtype=uint8, but should be uint32 [prod(uint8)]`

A PR, which had failing CI as a result, is [here](https://github.com/unifyai/ivy/pull/532).

A short discussion on this topic occurred [here](https://github.com/data-apis/array-api-tests/issues/10#issuecomment-1068469705).

**Comment by honno** [comment]
To clarify, this test _should_ be failing by default. As mentioned

> Ah this is interesting @djl11. The spec introduces a concept of "default unsigned integer" just for [`xp.prod()` ](https://data-apis.org/array-api/latest/API_specification/generated/signatures.statistical_functions.prod.html?highlight=prod) that mandates a `uint32` or `uint64` (respective to the [default integer](https://data-apis.org/array-api/latest/API_specification/data_types.html#default-data-types)) when `x=<uint array>, dtype=None`.
> 
> My initial impression is the test should remain as-is, because strictly PyTorch is non-compliant here. Of course we do support a lack of dtypes generally in the test suite, so maybe we could just skip this assertion if the relevant dtypes are not found. In any case, best to xfail/skip `test_pow` for now.

We assert output dtypes everywhere so I don't think we should just silently skip it if a `uint32`/`uint64` is not found.

The question to ask is should we add some mechanism to the suite (i.e. a CLI flag) to ignore this assertion when there is no default uint. I'm leaning torwards thinking it's not worth the hassle, and in any case think this is low-priority.

**Comment by djl11** [comment]
I am naturally biased towards thinking that adding a CI flag is worth it. Ivy uses the Array API Test suite as an [out-the-box submodule](https://github.com/unifyai/ivy/tree/e0640cf12c881aad80ddec24ff7e975d8055e09a/ivy_tests), and ideally we'd prefer to keep it that way, without the need to maintain our own fork with desired modifications. Currently, we need to keep test_prod [commented out](https://github.com/unifyai/ivy/blob/e0640cf12c881aad80ddec24ff7e975d8055e09a/ivy_tests/array_api_methods_to_test/statistical_functions.txt#L4) because of this error. If in principle you're happy to include such a CI flag, I can get someone on our team to make a PR for you to review and possible merge if happy? Are you okay for us to go ahead and have a stab at it @honno?

**Comment by pmeier** [comment]
If I read the spec correctly, this is the important part

> if x has an unsigned integer data type (e.g., `uint16`), the returned array must have an unsigned integer data type having the same number of bits as the default integer data type (e.g., if the default integer data type is `int32`, the returned array must have a `uint32` data type).

Can't you simply check if the projected dtype is defined *and* `FILTER_UNDEFINED_DTYPES = True` is set? If yes, you could simply skip the dtype check. The value check can be done unconditionally I think. Maybe you can also issue a warning if this skip is happening to make it visible.

**Comment by honno** [comment]
> Can't you simply check if the projected dtype is defined _and_ `FILTER_UNDEFINED_DTYPES = True` is set?

Hmm a silent skip made me queasy because we've only filtered _input_ dtypes before, and the output dtype has been explicitly specified for `prod()`... but maybe with a warning it is the better solution as it still acknowledges that `prod()` isn't quite compliant. My concern here is in practice array libraries tend to throw a million warnings for perfectly compliant operations that this'll go ignored, where a flag would ensure this non-compliant area is acknowledged.

**Comment by pmeier** [comment]
Given that the user has already acknowledged that the library is not compliant by setting `FILTER_UNDEFINED_DTYPES = True` IMO a warning should suffice.
