### ISSUE TITLE
Use equality instead of hasing for dtype helpers

### ISSUE THREAD

**Issue by honno** [data-apis/array-api-tests#111]
@asmeurer noted in https://github.com/data-apis/array-api-tests/pull/110#issuecomment-1097185020 that NumPy proper (i.e. `numpy`, as opposed to `numpy.array_api`) wasn't working with the test suite due to the [following code](
https://github.com/data-apis/array-api-tests/blob/98160117e839c4c1aa489b72a26951fbf66eccb1/array_api_tests/dtype_helpers.py#L120-L137). The problem was that the dtype attribute of NumPy-proper arrays were being used in conjuction with namespaced dtypes—these two are different objects, and thus have different hashes so they look like different keys in a `dict`.

```python
>>> import numpy as np
>>> dtypes_map = {np.int64: "foo"}
>>> dtypes_map[np.asarray(0).dtype]
KeyError
```

This behaviour is isn't specifically ruled out in the spec, as the [spec only says dtypes need equality](https://data-apis.org/array-api/latest/API_specification/data_types.html#data-type-objects), which NumPy-proper does conform to.

```python
>>> np.asarray(0).dtype == np.int64
True
```

So the test suite should phase out assumptions of namespaced dtypes and array dtypes sharing the same hash, instead relying on equality.

**Comment by asmeurer** [comment]
Could also be something to fix upstream. Technically a == b should imply hash(a) == hash(b), so NumPy isn't really following Python standard practices here.

**Comment by asmeurer** [comment]
I found https://github.com/numpy/numpy/issues/17864 which seems to be about this. Making the change here is still a good idea because the spec doesn't require hashing to begin with.
