### ISSUE TITLE
`test_matrix_norm` incorrect sampling

### ISSUE THREAD

**Issue by bicycleman15** [data-apis/array-api-tests#114]
https://github.com/data-apis/array-api-tests/blob/98160117e839c4c1aa489b72a26951fbf66eccb1/array_api_tests/test_linalg.py#L318
Shouldn't we also sample `-1`, right now we are sampling `-2` twice, seems to me like one of those `-2` should be `-1`. I might be wrong tho.

I am happy to make a PR for the same :)

**Comment by honno** [comment]
Thanks for pointing this out @bicycleman15, yea you're right. Would hold of a PR incase @asmeurer was going to rework `test_matrix_norm` in #101 anywho.
