### ISSUE TITLE
Signed zero special cases not always tested

### ISSUE THREAD

**Issue by Ishticode** [data-apis/array-api-tests#127]
Hi. I work with Ivy and noticed that the function `round` in `elementwise` has the behaviour shown in the code below which is against the requirements of [Array API Standard for round (special cases)](https://data-apis.org/array-api/latest/API_specification/generated/signatures.elementwise_functions.round.html?highlight=round#signatures.elementwise_functions.round) - but while using array_api_test suite,  `test_round` is passing and it doesn't seem to be noticed in `test_special_cases` either...

```
>>> import ivy
>>> ivy.set_backend("numpy")
>>> x = ivy.array([+0, -0, 0, 5])
>>> y = ivy.round(x)
>>> print(y)
ivy.array([0., 0., 0., 6.])
```
The result should be `ivy.array([+0., -0., 0., 6.])` for it to satisfy the Standard and should fail the test, right?
Could you kindly explain this...

**Comment by honno** [comment]
> `ivy.array()` tends to turn +/-0 into 0. As all arrays are Ivy arrays now, the test never got fed +/-0 I think.

Note your example is wrong

```python
>>> x = ivy.array([+0, -0, 0, 5])
```
is equivalent to

```python
>>> x = ivy.array([0, 0, 0, 5])
```
i.e. `+/-0` is literally an integer `0`. There is not such thing as a signed integer 0—that's a float thing.

```python
>>> +0 is 0
True
>>> +0. is 0
False
>>> type(+0)
int
>>> type(+0.)
float
```

**Comment by Ishticode** [comment]
Yes you're right. It is a floating thing. Even with floating example the result is as follows:
```
>>> import ivy
>>> ivy.set_backend("numpy")
>>> x = ivy.array([+0., -0., 0., 5.5])
>>> print(x)
>>> y = ivy.round(x)
>>> print(y)
ivy.array([ 0., -0.,  0.,  6.])
```

**Comment by honno** [comment]
> ```python
> >>> import ivy
> >>> ivy.set_backend("numpy")
> >>> x = ivy.array([+0., -0., 0., 5.5])
> >>> print(x)
> >>> y = ivy.round(x)
> >>> print(y)
> ivy.array([ 0., -0.,  0.,  6.])
> ```
> 
> Shouldn't +0. be returned for the first element?

Yep you're right, looks like a bug in `numpy.array_api`, and a bug in the test suite for not catching that!

**Comment by kgryte** [comment]
Maybe I am missing something, but, as `+0` and `0` are equivalent, I am not seeing off in the results above.

**Comment by honno** [comment]
> Maybe I am missing something, but, as `+0` and `0` are equivalent, I am not seeing anything off in the results above.

You're right, and that was OP's initial issue. But when using signed (float) zeroes, they did identify an actual issue I could reproduce - and that wasn't get tested in the suite (which is strange because the new special case tests have identified signed edge cases before).

```python
>>> from numpy import array_api as xp
>>> x = xp.asarray([+0., -0., 0., 5.5])
>>> out = xp.round(x)
>>> out
Array([ 0., -0.,  0.,  6.])
```

**Comment by Ishticode** [comment]
Thats all good. Just the part from the Array API standard page makes it seem like it is distinct/special.

It says:

For floating-point operands,

- If x_i is +0, the result is +0.

on this [page](https://data-apis.org/array-api/latest/API_specification/generated/signatures.elementwise_functions.round.html?highlight=round#signatures.elementwise_functions.round) for example.

So is there something I am not seeing as to why It is made a special case like this? 



Thank you for the answers above.

**Comment by honno** [comment]
I guess it became relevant enough that signs of zeroes could affect array consumers and thus interoperability. I think the fact negative zeroes exist and have their own special behaviour kinda propagates the need to special case positive zeroes too.

**Comment by Ishticode** [comment]
Ah I see. `+0.` is made to be special case to highlight the contrast with the special case `-0.` . I understand. Thnx for the expalantions. We can consider this concluded.
