### ISSUE TITLE
test_subtract failing due to binary_param_assert_dtype assuming input dtype if 'None' expected dtype

### ISSUE THREAD

**Issue by simonetgordon** [data-apis/array-api-tests#128]
Would it be possible to add an 'expected_dtype' argument to `binary_param_assert_dtype` in `test_subtract`? Since the default expected dtype is `None` and in`assert_dtype`, if this is the case, the dtype is taken to be the dtype of the input.

```
@pytest.mark.parametrize("ctx", make_binary_params("subtract", dh.numeric_dtypes))
@given(data=st.data())
def test_subtract(ctx, data):
    left = data.draw(ctx.left_strat, label=ctx.left_sym)
    right = data.draw(ctx.right_strat, label=ctx.right_sym)

    try:
        res = ctx.func(left, right)
    except OverflowError:
        reject()

    exp = res.dtype # new

    binary_param_assert_dtype(ctx, left, right, res, exp) # new
    binary_param_assert_shape(ctx, left, right, res)
```

**Comment by asmeurer** [comment]
`res.dtype` would be the computed dtype, not the expected dtype. The default value of None computes the expected dtype from the usual [type promotion rules](https://data-apis.org/array-api/latest/API_specification/type_promotion.html), which should be correct for subtract. Is this test asserting an incorrect thing for you?

**Comment by simonetgordon** [comment]
Yes I think the proper type promotion rules are being followed by the function itself. The left input has `uint8` dtype and the other has `int64`. This is the error message:
```
func_name = '__sub__', in_dtype = 'uint8', out_dtype = 'int64'
expected = 'uint8'
```
It seems the left input dtype to `subtract` is being used to define the expected dtype in the case of `None` dtype.

**Comment by asmeurer** [comment]
What are the inputs to `__sub__` that give that? Is it subtracting an array and an array or an array and a Python scalar?

**Comment by simonetgordon** [comment]
It was a scalar and an array. A colleague of mine has noticed an issue with our backend function implementation: the dtype wasn't being carried when the input array was being converted to a torch tensor. The test is passing now. Thanks for your help!

By the way, I noticed test_asarray_arrays is being skipped in your .yml file. Should we also skip this? It is failing most ivy backends too.

**Comment by honno** [comment]
> By the way, I noticed test_asarray_arrays is being skipped in your .yml file. Should we also skip this? It is failing most ivy backends too.

Probably yes. For NumPy (which is what our `.yml` workflow uses), `xp.asarray()` doesn't support `copy` fully yet, which is the case with all adopting libraries I believe right now.
