### ISSUE TITLE
0 dimensional arrays

### ISSUE THREAD

**Issue by mattbarrett98** [data-apis/array-api-tests#129]
Just ran into an issue with the handling of 0 dimensional arrays in one of our own tests (Ivy), but I don't believe this was ever an issue with the test suite. So I was just wondering do you test with 0 dimensional arrays?

**Comment by honno** [comment]
Yes almost always. The exceptions should be when a function doesn't support 0d arrays (e.g. in `linalg`), or when it was difficult to test for—you probably encountered a test where we previously didn't test 0d arrays but left it as a TODO, which was later implemented.
