### ISSUE TITLE
issue with `asarray` accepting list of arrays

### ISSUE THREAD

**Issue by sherry30** [data-apis/array-api-tests#142]
Hi,

I've come across an issue with `asarray` function. It seems like it is expected to work with list of arrays [here](https://github.com/data-apis/array-api-tests/blob/d71787e6ffca4c95522eff674b484c9297cadd11/array_api_tests/test_linalg.py#L224).
but in the docs, list of arrays isn't stated as an input type [here](https://data-apis.org/array-api/latest/API_specification/generated/signatures.creation_functions.asarray.html?highlight=asarray#signatures.creation_functions.asarray).
Let me know if this is an issue or if i misunderstood something,
Thanks

**Comment by asmeurer** [comment]
It says "nested sequence", which includes lists (see https://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range).

**Comment by sherry30** [comment]
Thanks for the answer but there's one thing I'm still confused about.
It says "NestedSequence[bool | int | float]" in the documentation, and also "May be a Python scalar, a (possibly nested) sequence of Python scalars" which made me think only nested sequence of scalars are allowed. But are nested sequence of arrays allowed as well?
Thanks in advance.

**Comment by asmeurer** [comment]
I think not, according to the current spec. Or rather, it isn't required, but there's nothing preventing a library from implementing it anyway. If you think it should be included, the place to request it would be the spec repo https://github.com/data-apis/array-api/issues (this is the tests repo).
