### ISSUE TITLE
Strange `test_linspace` assertion errors in jax

### ISSUE THREAD

**Issue by simonetgordon** [data-apis/array-api-tests#153]
Hi there,

`test_linspace` is failing for the jax backend for ivy, and hypothesis picks up two distinct failures:

1. `AssertionError: out[0]=ivy.array(nan), but should be 9.9792015476736e+291 [linspace(9.9792015476736e+291, -1.7976931348623157e+308, 2)]`

- raised on [line](https://github.com/data-apis/array-api-tests/blob/8ad6b629f6199afea808567e987b42a339366a7b/array_api_tests/test_creation_functions.py#L468)
- Falsifying example: `linspace(9.9792015476736e+291, -1.7976931348623157e+308, num =2, dtype= 'float64', endpoint=False)`
- The output for the same inputs in numpy is: `ivy.array([[ nan, -inf]])` (i.e. `out[0] = nan`, the same as in jax)

2. `AssertionError: out[0]=ivy.array(9.97920155e+291), should be ivy.array(nan) [linspace()]`

- raised on [line](https://github.com/data-apis/array-api-tests/blob/8ad6b629f6199afea808567e987b42a339366a7b/array_api_tests/test_creation_functions.py#L481): ` ph.assert_array_elements("linspace", out, expected)`
- Falsifying example: `linspace(9.9792015476736e+291, -1.7976931348623157e+308, num =1, dtype= 'float64', endpoint=False)`
- The output for the same inputs in numpy is: `ivy.array([[ nan]])` (i.e. `out[0] = nan`, different from the jax output)

I went about fixing the second failure as jax was diverging from numpy. However, I then (locally) got:
`AssertionError: out[0]=ivy.array(nan), but should be 9.9792015476736e+291 [linspace(9.9792015476736e+291, -1.7976931348623157e+308, 1)]`.

**Summary**: the expected value for `linspace` seems to vary from the numpy value when `start=9.9792015476736e+291` and `stop= -1.7976931348623157e+308` (close to float64 min value) with `num=1/2`, causing the test to fail for jax.

I can't reproduce these inputs for numpy `test_linspace`, so it is unclear if it would also fail for numpy or any other backend - jax is the only one that has raised this issue.

[Reference stack trace from ivy CI](https://github.com/unifyai/ivy/actions/runs/3321328156/jobs/5488845471) (click Run Array API Tests'

**Comment by asmeurer** [comment]
This looks related to https://github.com/data-apis/array-api-tests/pull/141. Can you confirm whether you're using a version of the suite that includes that change? If so, perhaps the restriction there needs to be tightened.

**Comment by simonetgordon** [comment]
@asmeurer in fact I'm not, I will update the submodule and get back to you. Thanks!

**Comment by simonetgordon** [comment]
@asmeurer the update seems to have fixed the linspace issue - no failures in the first few commits. Thanks!
