### ISSUE TITLE
Bump `array-api` submodule

### ISSUE THREAD

**Issue by honno** [data-apis/array-api-tests#187]
Should resolve https://github.com/data-apis/array-api/issues/631, clear up warnings, and remove some hacks in `_array_module.py`.

Ideally we utilise a stubs package, but that doesn't exist yet (https://github.com/data-apis/array-api/pull/472). The effort to bump `array-api` could be great enough that its worth me focusing on the stubs packaging, will see.

**Comment by asmeurer** [comment]
Another side-effect of this is that test_has_names currently doesn't check for any new functions added in the 2022 version of the spec.
