### ISSUE TITLE
No `default_complex` when `xp.asarray` is not present

### ISSUE THREAD

**Issue by mtsokol** [data-apis/array-api-tests#199]
Hi!
I noticed that there isn't a default complex dtype when `xp.asarray` is not present if branch. Is it on purpose, or could `default_complex` be added there? (it causes a setup failure when running tests for a lib without `xp.asarray`)

https://github.com/data-apis/array-api-tests/blob/b5ed713ae6be7fb45cebbcbabda035b39a265187/array_api_tests/dtype_helpers.py#L237

**Comment by honno** [comment]
Nice catch, yeah this would be a problem. Although generally if a library doesn't have `xp.asarray` not much is going to get tested anyway :sweat_smile:
