### ISSUE TITLE
Split the test suite for spec versions

### ISSUE THREAD

**Issue by asmeurer** [data-apis/array-api-tests#20]
The 2021 version of the spec is going to be finalized soon. The test suite isn't finished yet. However, we want to have a version of the test suite that runs only against 2021, so that people can run the suite without having to worry about features that are in the 2022 draft.

We should figure out some way to enable or disable test suite features. It would also be nice to be able to do this for the extensions, so that people can easily run the test suite without the linear algebra extension, for instance. Perhaps the best way to do this is using pytest marks? Another idea would be to split the parts of the suite into submodules so that people can run `pytest array_api_tests/2021` or `pytest array_api_tests/2021/extensions/linear_algebra`. For vendoring people could remove any submodules that aren't relevant. 

I'm guessing pytest marks will be better, but I need to investigate them to see how well suited they are for this.

**Comment by honno** [comment]
Something useful I learnt recently—we can specify markers for all test methods in a module via assigning the `pytestmark` variable once per-file.
```python
pytestmark = [...]
```

**Comment by honno** [comment]
I'll formalise my thoughts later, just to say we added versioning support to Hypothesis in https://github.com/HypothesisWorks/hypothesis/pull/3456, which I'll probably take inspiration from when working on this issue.
