### ISSUE TITLE
Support parsing special cases for `2022.12`/`draft` that we already test for in `2021.12`!

### ISSUE THREAD

**Issue by honno** [data-apis/array-api-tests#215]
After https://github.com/data-apis/array-api-tests/pull/213, it's not even that we can't parse newly introduced special cases, but that some changes to formatting mean special cases we test for `2021.12` aren't getting tested for `>2022.12` now.

**Comment by kgryte** [comment]
What changes to formatting affected special case parsing?

**Comment by honno** [comment]
> What changes to formatting affected special case parsing?

Good questions... turns out, none! I just introduced a bug when collecting special cases (used `break` over `continue` :facepalm:), resolved by https://github.com/data-apis/array-api-tests/pull/216.
