### ISSUE TITLE
`linalg.cholesky` not tested for complex dtypes

### ISSUE THREAD

**Issue by lucascolley** [data-apis/array-api-tests#228]
As reported in https://github.com/data-apis/array-api-compat/pull/61#issuecomment-1875887990, `linalg.cholesky` is only tested on real arrays, hence some bugs slipped through into both array-api-compat and numpy.array_api.

**Comment by lucascolley** [comment]
relevant lines:
https://github.com/data-apis/array-api-tests/blob/d295a0a66cd82a43e84c1b8d73ca198cc45e9d23/array_api_tests/test_linalg.py#L126-L130
https://github.com/data-apis/array-api-tests/blob/d295a0a66cd82a43e84c1b8d73ca198cc45e9d23/array_api_tests/hypothesis_helpers.py#L314

**Comment by lucascolley** [comment]
okay cool, so it seems like Ralf's initial diagnosis was incorrect. I don't know why the linked bug was able to slip through, then.

**Comment by asmeurer** [comment]
I think this is something that I fixed a few months ago.
