### ISSUE TITLE
Make two_mutual_arrays accept a dtypes strategy as input

### ISSUE THREAD

**Issue by asmeurer** [data-apis/array-api-tests#33]
two_mutual_arrays accepts a list of dtype objects rather than a strategy for generating dtypes. This is somewhat annoying, as everything else uses the dtypes strategies.

A issue with this is that it currently ignores the filtering that is done in the dtype strategies. This makes any test using it fail in pytorch, which doesn't have uint8. 

If we can make it accept a dtypes strategy, that would be great. We may just need to have an internal mapping of dtype strategies to promotable dtype strategies. Or maybe we can just draw a dtype then draw another dtype that is promotable compatible with it.

**Comment by asmeurer** [comment]
Let's leave this open for making two_mutual_arrays accept a strategy as input. It's something that confuses me almost every time I run into it, so it would be good to change it if at all possible.

**Comment by honno** [comment]
Hmm, so I can't figure out how to do this nicely. Both the dtype strategies in `hypother_helpers.py` and in `xps.*` return generic strategies with seemingly no way (definitely not public) to distinguish between them (and thus map them to their respective dtype objects).

I wrote #36 at least to raise a consistent error.

**Comment by honno** [comment]
I still don't think this is feasible/worth doing, and hopefully my custom error and more experience mitigates the problem you were having.
