### ISSUE TITLE
Test special cases for statistical functions

### ISSUE THREAD

**Issue by honno** [data-apis/array-api-tests#41]
There are a few special cases in [statistical functions](https://data-apis.org/array-api/latest/API_specification/statistical_functions.html) that we don't cover.

**Comment by asmeurer** [comment]
Which functions outside of elementwise have special cases?

**Comment by honno** [comment]
> Which functions outside of elementwise have special cases?

Statistical functions (and I realise only those, I've updated the issue accordingly.)
