### ISSUE TITLE
Clear up CI

### ISSUE THREAD

**Issue by honno** [data-apis/array-api-tests#49]
~IMO it's not worth touching CI as the 1st spec release is so close as well as NumPy, but here's an issue to keep us accountable when time time comes :)~ well it's 2022 now so

- [ ] Update stubs
  - [ ] Create a custom pre-commit hook to check/fix outdated stubs (done something [similar](https://github.com/honno/asciidump/blob/main/make_style.py))
- [ ] Identify remaining tests to xfail for the NumPy job

**Comment by asmeurer** [comment]
I wouldn't make the stubs required to commit. The problem is that sometimes the generate script needs to be updated first.

**Comment by honno** [comment]
> I wouldn't make the stubs required to commit. The problem is that sometimes the generate script needs to be updated first.

Ah I don't mean you need to always commit the stubs, but that a hook will check when you need to update them (and thus commit). This could first check whether your local spec is up-to-date. Things might be slow but some quick checks and simple caching. I think this would save us a lot of pain down the road in regards to CI failing.

(and defo a pre-commit hook is not a big priority)

**Comment by honno** [comment]
RE NumPy workflow: I think I will resolve #64 and make a pytest marker that just runs "primary" tests, as that makes writing workflows much easier. We can pin on released versions now i.e. `1.22.1`.

RE stubs: let's wait on the RST conversion first.
