### ISSUE TITLE
Meta tests

### ISSUE THREAD

**Issue by asmeurer** [data-apis/array-api-tests#5]
Given the complexity of some of the tests, it would be a good idea to test that they are actually testing what we expect. This entails two things

- Faking out modules with all the known errors and making sure that the corresponding test fails as expected
- Faking out a module that doesn't give any errors

I don't actually know how to do the first one. Can pytest be used as a library, to run just a single test?

For the second one, I don't know if we can actually do it. It would amount to writing a module that actually conforms to the spec. Such an endeavor might be out of scope for this project.

**Comment by honno** [comment]
I feel the test suite now does well with

1. meta tests for the more awkward utils we use
2. sanity checks with explanatory messages when test logic gets complicated

so I'll close this.
