### ISSUE TITLE
Hypothesis MultipleFailures Uninformative Stack Trace

### ISSUE THREAD

**Issue by djl11** [data-apis/array-api-tests#99]
I frequently get stack traces such as the following when running tests. These traces don't include the failing lines of code, which is preventing me from being able to find the problems.

> ivy_tests/test_array_api/array_api_tests/test_operators_and_elementwise_functions.py::test_isfinite FAILED [100%]
ivy_tests/test_array_api/array_api_tests/test_operators_and_elementwise_functions.py:908 (test_isfinite)
@ given(xps.arrays(dtype=xps.numeric_dtypes(), shape=hh.shapes()))
>   def test_isfinite(x):
E   hypothesis.errors.MultipleFailures: Hypothesis found 3 distinct failures.
ivy_tests/test_array_api/array_api_tests/test_operators_and_elementwise_functions.py:910: MultipleFailures

This issue may be better suited in the Hypothesis repo, but thought I would add here in case others using the array api tests run into the same issue when trying to debug the tests. Is there a good way to find the problematic code from this stack trace?

**Comment by asmeurer** [comment]
Usually the errors are shown somewhere below those lines. Can you maybe post the full test output in a gist so I can see what it looks like.

**Comment by djl11** [comment]
Okay this must be an issue with PyCharm as I am able to get the full stack trace when running via the terminal. Will close this issue and work out what's going on with my IDE, thanks!

**Comment by djl11** [comment]
[This](https://youtrack.jetbrains.com/issue/PY-48468#focus=Comments-27-4890623.0-0) is the exact issue I've been facing in case it's useful to any PyCharm users. The issue is specific to hypothesis.
